### ISSUE TITLE
Rename project to jupyterhub-home-nfs

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/jupyterhub-home-nfs#2]
Since this is primarily to be used with `jupyterhub` rather than `jupyter` in general, I'd like us to rename this project to be `jupyterhub-home-nfs` rather than `jupyter-home-nfs`. Earlier the better, before a lot of deployments have gone out, as this would also require renaming the helm chart.

**Comment by sunu** [comment]
@yuvipanda Sounds good! Should we also consider moving the repo to somewhere more appropriate?

**Comment by yuvipanda** [comment]
@sunu how do you feel about moving it into the 2i2c-org?

**Comment by sunu** [comment]
@yuvipanda yes, let's do that!
